# Generated by Django 3.1.6 on 2021-02-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('delimeter', models.CharField(choices=[('Comma (,)', 'Comma'), ('Tab (   )', 'Tab'), ('Semicolon (;)', 'Semicolon'), ('Pipe (|)    ', 'Pipe')], default='Comma (,)', max_length=20)),
                ('quote', models.CharField(choices=[("Single-quote (')", 'Single'), ('Double-qoute (")', 'Double')], default='Double-qoute (")', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default='django.utils.timezone.now')),
                ('status', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='csv_gen.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('col_type', models.CharField(choices=[('Full name', 'Fullname'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domainname'), ('Phone number', 'Phonenumber'), ('Company name', 'Companyname'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], default='Text', max_length=20)),
                ('filter', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(blank=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='csv_gen.schema')),
            ],
        ),
    ]
