# Generated by Django 3.1.6 on 2021-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='schema',
            name='delimeter',
            field=models.CharField(choices=[(',', 'Comma (,)'), ('\t', 'Tab (   )'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], default=',', max_length=20),
        ),
        migrations.AlterField(
            model_name='schema',
            name='quote',
            field=models.CharField(choices=[("'", "Single-quote (')"), ('"', 'Double-qoute (")')], default='"', max_length=20),
        ),
    ]
