# Generated by Django 3.1.6 on 2021-02-15 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0002_auto_20210215_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 15, 21, 13, 17, 355684)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Proccessing', 'Proccessing'), ('Ready', 'Ready')], default='Proccessing', max_length=20),
        ),
    ]
