# Generated by Django 3.1.6 on 2021-02-15 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0003_auto_20210215_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 15, 22, 11, 24, 697802)),
        ),
    ]
