# Generated by Django 3.1.6 on 2021-02-17 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0004_auto_20210215_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='filter',
            new_name='col_filter',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 11, 36, 11, 205855)),
        ),
    ]
