# Generated by Django 3.1.6 on 2021-02-17 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0006_auto_20210217_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 12, 14, 11, 247016)),
        ),
        migrations.AlterField(
            model_name='schema',
            name='quote',
            field=models.CharField(choices=[("'", "Single-quote (')"), ('"', 'Double-quote (")')], default='"', max_length=20),
        ),
    ]
